# Generated by Django 3.2.2 on 2022-05-30 02:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_api', '0011_alter_credential_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 2, 9, 13, 940811, tzinfo=utc)),
        ),
    ]
