# Generated by Django 3.2.2 on 2022-05-30 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_api', '0014_alter_credential_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='credential',
            name='expires_in',
        ),
    ]
