# Generated by Django 3.2.2 on 2022-06-02 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_api', '0016_auto_20220530_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='facebook_id',
            field=models.CharField(blank=True, db_column='User Facebook ID', max_length=500),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('page_id', models.IntegerField(db_column='Facebook Page ID')),
                ('page_access_token', models.CharField(blank=True, db_column='Facebook Access Token', max_length=500)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='facebook_api.credential', verbose_name='Credential')),
            ],
        ),
    ]
