# Generated by Django 3.2.2 on 2022-06-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_api', '0017_auto_20220602_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Facebook Page Name'),
        ),
        migrations.AddField(
            model_name='page',
            name='page_picture',
            field=models.CharField(blank=True, max_length=255, verbose_name='Facebook Page Picture'),
        ),
        migrations.AddField(
            model_name='page',
            name='url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Facebook Page Link'),
        ),
        migrations.AlterField(
            model_name='page',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_access_token',
            field=models.CharField(blank=True, max_length=500, verbose_name='Facebook Access Token'),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_id',
            field=models.IntegerField(verbose_name='Facebook Page ID'),
        ),
    ]
