# Generated by Django 3.2.2 on 2022-06-02 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_api', '0021_alter_page_page_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='page_picture',
            new_name='picture',
        ),
    ]
