# Generated by Django 3.2.2 on 2022-06-02 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_api', '0022_rename_page_picture_page_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='page_name',
            new_name='name',
        ),
    ]
