# Generated by Django 3.2.2 on 2022-06-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_api', '0023_rename_page_name_page_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='post_respondidos',
            field=models.IntegerField(default=0, verbose_name='Posts Respondidos'),
        ),
    ]
