# Generated by Django 3.2.2 on 2022-06-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_api', '0025_rename_post_respondidos_page_posts_respondidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='mensajes_respondidos',
            field=models.IntegerField(default=0, verbose_name='Mensajes Respondidos'),
        ),
    ]
