# Generated by Django 3.2.2 on 2022-06-03 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_api', '0026_page_mensajes_respondidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=50, verbose_name='Tag')),
                ('message', models.CharField(blank=True, max_length=500, verbose_name='Message')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='facebook_api.page', verbose_name='Page')),
            ],
        ),
    ]
