# Generated by Django 3.2.2 on 2022-06-07 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_api', '0028_rename_page_access_token_page_access_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(blank=True, db_column='User Facebook ID', max_length=500)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='facebook_api.page', verbose_name='Page')),
            ],
        ),
    ]
