# Generated by Django 3.2.2 on 2022-06-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_api', '0030_auto_20220607_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='User Facebook Name'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_picture',
            field=models.CharField(blank=True, max_length=500, verbose_name='User Facebook Picture'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(max_length=500, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_id',
            field=models.CharField(max_length=500, verbose_name='User Facebook ID'),
        ),
    ]
