version: '3.3'

networks:
  isolation-network:
    name: isolation-network
    driver: bridge

services:
  facebook-api:
    tty: true
    build:
      context: .
      dockerfile: docker/Dockerfile

    image: facebook-api
    hostname: inove
    
    ports:
      - "8051:5000"

    expose:
      - "5000"

    env_file:
      - api/.env

    networks: 
      - isolation-network

    container_name: facebook-api
    volumes:
      - type: bind
        source: .
        target: /opt/back_end